server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.56.101
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: localhost

leyou:
  sms:
    # AccessKeyId
    accessKeyId: JWffwFJIwada
    # AccessKeySecret
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ
    # 签名名称
    signName: 乐优商城
    # 模板名称
    verifyCodeTemplate: SMS_133976814